apiVersion: v2
name: indigo-server
description: A Helm chart for deploying the API Gateway service
type: application
version: 0.1.0
appVersion: "v0.0.11"

dependencies:
  - name: postgresql
    version: "16.7.27"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: valkey-cluster
    version: "3.0.24"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
    alias: valkey
