{{- if and .Values.inference.enabled .Values.inference.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.inference.storage.pvcName }}
  labels:
    {{- include "indigo-server.labels" . | nindent 4 }}
    component: inference-storage
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.inference.storage.storageClassName }}
  storageClassName: {{ .Values.inference.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.inference.storage.size }}
{{- end }}