{{- if .Values.inference.enabled }}
{{- range .Values.inference.models }}
{{- if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
  labels:
    {{- include "indigo-server.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "indigo-server.selectorLabels" $ | nindent 4 }}
    model: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .service.port | default 8000 }}
      targetPort: {{ .service.targetPort | default 8000 }}
  type: {{ .service.type | default "ClusterIP" }}
{{- end }}
{{- end }}
{{- end }}