{{- if .Values.gateway.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "indigo-server.fullname" . }}
  labels:
    {{- include "indigo-server.labels" . | nindent 4 }}
spec:
  {{- if .Values.gateway.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.gateway.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.gateway.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.gateway.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "indigo-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}