{{- if .Values.gateway.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "indigo-server.serviceAccountName" . }}
  labels:
    {{- include "indigo-server.labels" . | nindent 4 }}
  {{- with .Values.gateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.gateway.serviceAccount.automount }}
{{- end }}